### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by DennisD8** [jonnyrider/eufy_vacuum_g10#2]
Hi, 
Thanks for the integration!
But i am running into some issues.
When added to HA i can see the status (docked/cleaning) Battery, and Fan. These also change when i start the vaccuum with the eufyhome app.

But it seems that i cannot send the start/stop etc commands.
When i check the logs i see the following errors:

```
2022-01-17 20:58:43 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing eufy_vacuum_g10/recorder.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.eufy_robovac_g10.recorder'
2022-01-17 20:58:43 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing eufy_vacuum_g10/system_health.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.eufy_robovac_g10.system_health'
2022-01-17 20:58:43 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing eufy_vacuum_g10/logbook.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.eufy_robovac_g10.logbook'
2022-01-17 20:58:43 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing eufy_vacuum_g10/media_source.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.eufy_robovac_g10.media_source'
2022-01-17 20:58:43 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing eufy_vacuum_g10/group.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.eufy_robovac_g10.group'
2022-01-17 21:11:46 ERROR (MainThread) [custom_components.eufy_robovac_g10.tuya] 'utf-8' codec can't decode byte 0xf0 in position 7: invalid continuation byte
2022-01-17 21:11:46 ERROR (MainThread) [custom_components.eufy_robovac_g10.tuya] Failed to decrypt message from MYIDCODE (192.168.0.21:6668)
2022-01-17 21:12:06 ERROR (MainThread) [custom_components.eufy_robovac_g10.tuya] 'utf-8' codec can't decode byte 0xf0 in position 7: invalid continuation byte
2022-01-17 21:12:06 ERROR (MainThread) [custom_components.eufy_robovac_g10.tuya] Failed to decrypt message from MYIDCODE  (192.168.0.21:6668)
```
Offcource the folder config/custom_components/eufy_robovac_g10 
excists with all files from you.
Any idea what i can do?

**Comment by jonnyrider** [comment]
Can you please send your Home Assistant configuration? I'll take a look.

**Comment by DennisD8** [comment]
Do you mean copy of my configuration.yaml?

**Comment by jonnyrider** [comment]
Yes, please

**Comment by DennisD8** [comment]
Ok, this is my configuration.yaml
ID's and secrets hidden

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  
eufy_vacuum_g10:
  devices:
  - name: Robomop
    address: 192.168.0.21
    access_token: 892d6633949f0ed7
    id: bf30ea984838fe3b8dship
    type: T2118
```

**Comment by jonnyrider** [comment]
Sorry for the delay. I no longer have this vacuum so can no longer look into this!
